// Static catalog used to power the slash-command autocomplete.
// Keep alphabetical within each category for predictability.

export const SLASH_COMMANDS = [
  { cmd: '/help',        desc: 'Show help summary',                              cat: 'Info'     },
  { cmd: '/commands',    desc: 'List all available commands',                    cat: 'Info'     },
  { cmd: '/status',      desc: 'Show runtime execution / quota info',            cat: 'Info'     },
  { cmd: '/whoami',      desc: 'Show your sender ID',                            cat: 'Info'     },
  { cmd: '/tools',       desc: 'Display agent capabilities',                     cat: 'Info'     },
  { cmd: '/usage',       desc: 'Show token usage and cost summary',              cat: 'Info'     },
  { cmd: '/context',     desc: 'Explain context assembly',                       cat: 'Info'     },
  { cmd: '/new',         desc: 'Start a new session',                            cat: 'Session'  },
  { cmd: '/reset',       desc: 'Reset session history',                          cat: 'Session'  },
  { cmd: '/compact',     desc: 'Compress session context',                       cat: 'Session'  },
  { cmd: '/stop',        desc: 'Abort the current run',                          cat: 'Session'  },
  { cmd: '/model',       desc: 'Show or set current model',                      cat: 'Model'    },
  { cmd: '/models',      desc: 'List available models and providers',            cat: 'Model'    },
  { cmd: '/think',       desc: 'Set thinking level (off / low / medium / high)', cat: 'Model'    },
  { cmd: '/fast',        desc: 'Toggle fast mode on or off',                     cat: 'Model'    },
  { cmd: '/reasoning',   desc: 'Toggle reasoning output visibility',             cat: 'Model'    },
  { cmd: '/elevated',    desc: 'Toggle elevated permission mode',                cat: 'Model'    },
  { cmd: '/verbose',     desc: 'Toggle verbose output',                          cat: 'Output'   },
  { cmd: '/trace',       desc: 'Toggle plugin trace output',                     cat: 'Output'   },
  { cmd: '/btw',         desc: 'Ask a side question without changing context',   cat: 'Advanced' },
  { cmd: '/skill',       desc: 'Run a skill by name',                            cat: 'Advanced' },
  { cmd: '/queue',       desc: 'Manage queue behavior',                          cat: 'Advanced' },
  { cmd: '/steer',       desc: 'Inject guidance into an active run',             cat: 'Advanced' },
  { cmd: '/subagents',   desc: 'Manage sub-agent runs',                          cat: 'Advanced' },
  { cmd: '/approve',     desc: 'Resolve exec approval prompts',                  cat: 'Advanced' },
  { cmd: '/config',      desc: 'Read or write openclaw.json config',             cat: 'Admin'    },
  { cmd: '/plugins',     desc: 'Inspect or mutate plugins',                      cat: 'Admin'    },
  { cmd: '/restart',     desc: 'Restart OpenClaw',                               cat: 'Admin'    },
  { cmd: '/diagnostics', desc: 'Generate a support diagnostics report',          cat: 'Admin'    },
  { cmd: '/bash',        desc: 'Run a shell command (requires bash enabled)',    cat: 'Admin'    },
];
